json.id @car.id
json.make @car.make
json.model @car.model
json.year @car.year
json.mileage @car.mileage
json.price @car.price
json.transmission @car.transmission
json.drivetrain @car.drivetrain
json.body_style @car.body_style
json.image_url @car.image_url
